- name: Cisco IOS SSH - show running-config
  ios_command:
    commands: 'show running-config'
  register: output
  ignore_errors: yes

- name: Cisco IOS SSH - Save the output
  vars:
    clean_config: "{{ output.stdout[0]|clean_config(clean_patterns) }}"
  local_action: copy content={{clean_config}} dest={{backup_dir}}/{{file_name}}
  when: output.failed == false
  ignore_errors: yes

- name: Cisco IOS SSH - Process the file
  command:
    argv:
      - python3
      - scripts/netconf-backup.py
      - "{{ inventory_hostname }}"
      - "{{ file_name }}"
      - "{{ backup_dir }}"
      - "{{ keep_local_history }}"
      - "{{ historic_files_to_keep }}"
  delegate_to: localhost
  when: output.failed == false
  ignore_errors: yes

- name: Cisco IOS SSH - Send Mail alert if host backup failed
  vars:
    os: "Cisco IOS SSH"
    step: "fail"
  import_tasks: netconf-backup-send-mail.yml
  when: output.failed == true and alert_mail == "yes"

- name: Cisco IOS SSH - Send Slack alert if host backup failed
  vars:
    os: "Cisco IOS SSH"
    step: "fail"
  import_tasks: netconf-backup-msg-slack.yml
  when: output.failed == true and alert_slack == "yes"